### ISSUE TITLE
Installing Geth on OSX 10.10.1 - piping from curl to bash gives 'Bad File Descriptor' error

### ISSUE THREAD

**Issue by lukasmarshall** [ethereum/ethereum-org#120]
When running the standard install command on OSX:

bash <(curl https://install-geth.ethereum.org -L)

an issue with piping from curl to bash seems to give this error:

bash: /dev/fd/63: Bad file descriptor

A workaround is to pipe the installer script to a local file then run the script locally, ie.
curl https://install-geth.ethereum.org -L > install.sh
bash install.sh

**Comment by linagee** [comment]
It seems other projects have suffered from this OSX-ism as well. It looks like maybe it's just the directory you run it from maybe? (I'd have no way to test.)

https://github.com/Homebrew/homebrew/issues/14923
