### ISSUE TITLE
Missing GMP symlink in OSX 10.10.1 causes error when running 'geth console'

### ISSUE THREAD

**Issue by lukasmarshall** [ethereum/ethereum-org#121]
When running 'geth console' on OSX 10.10.1, a missing symlink between the currently-installed GMP library and homebrew causes the following error:

dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /usr/local/bin/geth
  Reason: image not found

a fix is to run:
sudo brew link gmp

**Comment by linagee** [comment]
Maybe this brew command to install gmp should be added to the one line installer?
https://github.com/ethereum/frontier-release/blob/master/bin/install-go.sh#L326

add inside of osx_installer() or osx_dependency_installer()

**Comment by caktux** [comment]
gmp is already in the formula's dependencies, and **never** run brew with sudo, which was probably why it wasn't linked since your brew installation is probably broken in the first place
