### ISSUE TITLE
Docs should say what needs to be in the testnet genesis block

### ISSUE THREAD

**Issue by plato-cambrian** [ethereum/ethereum-org#129]
Hi, I am totally new to Etherium and am walking through your docs. I am on the [CLI](https://www.ethereum.org/cli) page. Pretty much the first thing is "you should make a private testnet to avoid spending real ether." 

i would like to improve the page to help other devs who have no idea what this genesis block is, but I would rather not say 'google etherium genesis block json and pick the top result and modify it', surely there is an example committed in a repo, or a wiki page with documentation? 

edit: found an example via https://github.com/ethereum/genesis_block_generator/issues/16

**Comment by paulmorriss** [comment]
I found this tutorial http://adeduke.com/2015/08/how-to-create-a-private-ethereum-chain/ which explains it well (and other things too). Could the essential information from that page go somewhere on ethereum.org?

**Comment by mitar** [comment]
Yes, this is really bad. In the guide there is a link to [blog post](https://blog.ethereum.org/2015/07/27/final-steps/) how to generate the genesis file. Which I followed. And as a result got a genesis file with mining complexity so high that I did not get no first block after few hours of running geth. Go figure out what is wrong. There should be a simple json file simply attached (there are already many commands you have to run), or even geth should just do it for you as a command line switch. And also it should be documented how long is the first block on a testnet expected to take. How should I know that it should be 15 seconds and that it is something wrong, if I am new to Ethereum?
