### ISSUE TITLE
code does not follow solidity style guide...

### ISSUE THREAD

**Issue by MrChico** [ethereum/ethereum-org#213]
...or should abstract contracts not also be named in CapWords?
The contract tokenRecipient at https://ethereum.org/token, contract token at https://ethereum.org/crowdsale and contract owned at the dao page are all not following this convention

**Comment by alexvandesande** [comment]
Can you be more precise? Are you talking about the fact that contract Owned doesn't start with uppercase? That is a good point.

**Comment by MrChico** [comment]
Yes, exactly. But you do seem to be quite consistent in using lower case for abstract contracts, so I wasn't sure if it was intentional or not

**Comment by alexvandesande** [comment]
I never questioned it to be true, I just copied from elsewhere. Is there a
style guide somewhere?

On Mon, Mar 21, 2016 at 7:11 PM, MrChico <notifications@github.com> wrote:

> Yes, exactly. But you do seem to be quite consistent in using lower case
> for abstract contracts, so I wasn't sure if it was intentional or not
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/ethereum-org/issues/213#issuecomment-199511346>
>



-- 

Alex Van de Sande
UX Designer

**Comment by MrChico** [comment]
http://solidity.readthedocs.org/en/latest/style-guide.html?
