### ISSUE TITLE
Variable not declared in Token tutorial

### ISSUE THREAD

**Issue by jefflau** [ethereum/ethereum-org#218]
In the token tutorial that i've been following step by step: https://ethereum.org/token

At this code snippet we introduce the `totalSupply` variable, but we haven't declared it yet at the top of the contract. It is there in the full source code, but might be confusing for someone completely new.

```solidity
function mintToken(address target, uint256 mintedAmount) onlyOwner {
    balanceOf[target] += mintedAmount;  
    totalSupply += mintedAmount;
    Transfer(0, owner, mintedAmount);
    Transfer(owner, target, mintedAmount);
}
```

**Comment by bobsummerwill** [comment]
Hey @jefflau,
Could you create a pull-request with a suggested change, please?   Thanks!

**Comment by jefflau** [comment]
Here you go @bobsummerwill 

https://github.com/ethereum/ethereum-org/pull/221

**Comment by pascalvanhecke** [comment]
This issue can be closed given https://github.com/ethereum/ethereum-org/pull/221
