### ISSUE TITLE
Low resolution Mix resources are gone.

### ISSUE THREAD

**Issue by EtherTyper** [ethereum/ethereum-org#237]
![mix no-show image](https://cloud.githubusercontent.com/assets/16024539/14748962/74a4c982-0882-11e6-91b8-6af1960623cb.PNG)

> "The site does uses the `@2x` images, but only when it detects a high resolution display. Look on the @media queries section." - @alexvandesande on PR #236

There **are only** ```turbo-0X@2x.png``` images in the repository, no low-res images available to display on other computers. Is there any way for you to add these resources to the repository, or to produce a workaround so that it _doesn't_ attempt to use such nonexistent resources at all? The site does not look good in Inspect Element, either! :laughing: 

Thanks,
The @ethertyper

**Comment by alexvandesande** [comment]
Ah that's the problem! I didn't realize those were gone!

Will fix it, thanks!

**Comment by EtherTyper** [comment]
@alexvandesande You're welcome! :smiley:

**Comment by alexvandesande** [comment]
Fixing it with https://github.com/ethereum/ethereum-org/pull/239

**Comment by EtherTyper** [comment]
Awesome! 👍
