### ISSUE TITLE
Needs new Screenshot

### ISSUE THREAD

**Issue by EtherTyper** [ethereum/ethereum-org#241]
In the README, I reattached the link to the Frontier screenshot to semonstrate the site in action, but I think that the screenshot should be updated to the Homestead website.

**Comment by alexvandesande** [comment]
Good point:
<img width="721" alt="captura de tela 2016-05-11 as 12 34 52 pm" src="https://cloud.githubusercontent.com/assets/112898/15186824/f2c9ba56-1774-11e6-944b-8309c6b9114e.png">
