### ISSUE TITLE
Update Repo subtitle

### ISSUE THREAD

**Issue by luclu** [ethereum/ethereum-org#243]
Just cosmetic..
Still reads Frontier release website.

**Comment by alexvandesande** [comment]
What do you mean by subtitle? Is this about this: https://github.com/ethereum/ethereum-org/issues/241 ?

**Comment by luclu** [comment]
On the repo's code tab just over the file explorer and overview strip. This subtitle is alsow shown on searches, internally and probably externally from github.

**Comment by EtherTyper** [comment]
@alexvandesande I think @luclu means the "Project Description," the value that GitHub uses to generate the README when you generate a repo. It's not related to the Git repository itself, but rather the GitHub API, so you can just fix it by clicking the "— [Edit](#)" link to its right, if you have rights to the repository.

**Comment by alexvandesande** [comment]
done!
