### ISSUE TITLE
Wallet Download links still point to 0.7.1

### ISSUE THREAD

**Issue by luclu** [ethereum/ethereum-org#244]
At least for OSX.

**Comment by luclu** [comment]
Needs to be pushed live.

**Comment by alexvandesande** [comment]
I'll ping taylor to have it pushed

**Comment by alexvandesande** [comment]
Fixed

On Wed, May 4, 2016 at 11:31 AM, Luca Zeug <notifications@github.com> wrote:

> Needs to be pushed live.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/ethereum-org/issues/244#issuecomment-216883238>
>



-- 

Alex Van de Sande
UX Designer
