### ISSUE TITLE
receiveApproval in token tutorial code, but not explained

### ISSUE THREAD

**Issue by miohtama** [ethereum/ethereum-org#251]
The tutorial has "spend behalf" element:

       contract tokenRecipient { function receiveApproval(address _from, uint256 _value, address _token, bytes _extraData); }

However this is not explained in the tutorial text and unnecessarily confuses the reader?

**Comment by alexvandesande** [comment]
these are part of a proposed standard and we haven't written about it yet because it's not widely accepted
