### ISSUE TITLE
cpp-ethereum links need updating

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/ethereum-org#285]
So @alexvandesande - Does ethereum.org point to specific URLs?    Or maybe just 'latest' for cpp-ethereum (and that is weird because 1.3.0 is in an irregular location?

Also - I see the Mix link is still there :-)

See https://github.com/ethereum/webthree-umbrella/issues/706#issuecomment-240947201.

**Comment by 5chdn** [comment]
The cpp-ethereum client does not provide any releases since summer and 1.3.1 never happened. We should remove this from future versions of the site.

**Comment by ryanio** [comment]
I believe this issue can be closed, all cpp-ethereum links in repo are pointing to latest

**Comment by cvshanab** [comment]
case closed?
