### ISSUE TITLE
update Ethereum Wallet from 0.8.2 to 0.8.4

### ISSUE THREAD

**Issue by luclu** [ethereum/ethereum-org#290]

**Comment by bneiluj** [comment]
I think this issue is outdated. 

Firstly: Ethereum wallet is at ```v0.8.7``` [https://github.com/ethereum/mist/releases/tag/v0.8.7](url)
Secondly: Links will always be updated with the latest version of the wallet. 
Thirdly: There is no ```0.8.2``` in the current version of the project.
