### ISSUE TITLE
add support others languages

### ISSUE THREAD

**Issue by EvertonMelo** [ethereum/ethereum-org#292]
add more languages to the site, so we can increase the popularity with few resources.

Suggested additional languages: Portuguese, Spanish, Italian.

**Comment by asamitier** [comment]
I think so as well

**Comment by MarcioPorto** [comment]
I would be happy to help add support for Portuguese. I think adding support for other languages is a great way to reach more people and make them more aware of the project. Are there any current plans to add this?

**Comment by EvertonMelo** [comment]
@MarcioPorto 

had the whitepaper, but some asshole deleted:

https://webcache.googleusercontent.com/search?q=cache:4DPepv6r11AJ:https://github.com/ethereum/wiki/wiki/%255BPortuguese%255D-White-Paper+&cd=1&hl=pt-BR&ct=clnk&gl=br

**Comment by EvertonMelo** [comment]
@evertonfraga 

tudo bem Chará? 

na sua opinião qual é a melhor forma para começar isso?? 
i18n??? 

eu ja comecei algo em: 

https://github.com/ethereum/wiki/wiki/%5BPortuguese%5D-White-Paper
Mas tudo la é bem limitado. 

o legal do site é que da mais visibilidade a quem não tem conhecimento técnico. 

se bem que para esse projeto isso não importa [link](https://github.com/ethereum/wiki/issues/103)

o que vale aqui são [números](https://github.com/ethereum/wiki/wiki#issues-and-pull-requests) de contribuições não qualidade.

**Comment by evertonfraga** [comment]
Rapaz, tudo bem?

por enquanto acho que a Wiki é o melhor lugar mesmo. Existe um grupo de trabalho que está repensando o site, e acho que fica pronto dentro de alguns meses. Imagino que esteja sendo pensado levando i18n em conta. Quando chegar a hora saberemos e fazemos um esforço da comunidade BR-BR-HUE pra traduzir ;)


Ah, e mandou bem traduzindo a wiki!
