### ISSUE TITLE
Integrating Ethereum with Mycelium mobile wallet? Where do we stand? 

### ISSUE THREAD

**Issue by Nogreedy** [ethereum/ethereum-org#318]
Hello,
https://www.reddit.com/r/ethereum/comments/4gojnu/mycelium_mobile_wallet_will_implement_ethereum/
https://www.reddit.com/r/Bitcoin/comments/4gkxox/mycelium_new_wallet_announcement/
Who is in charge?
Are you (or others ETH devs) in contact with Mycelium team?
Thanks in advance for your answer.
PS : my question is specifically about Mycelium wallet... I know there are others ETH mobile wallets (Jaxx...).

**Comment by alexvandesande** [comment]
Hi Nogreedy! This is really not the appropriate place for this. You should ask the Mycellium development team about it.

**Comment by Nogreedy** [comment]
@alexvandesande Thanks .
I did...
https://github.com/mycelium-com/wallet/issues/337
but I think it's a very important question...
