### ISSUE TITLE
Remove burn functions from token example

### ISSUE THREAD

**Issue by StevenBerryman** [ethereum/ethereum-org#583]
Not sure why these two functions are in the first version of the token code for a number of reasons:

1) First function doesn't compile. _from doesn't exist as I assume it should be msg.sender
2) What do these functions actually do? It seems to be taken ethers in and burning the ether amount from the token balance. Won't the ethers end up stuck on the token contract?
3) These functions are not mentioned in the docs below so I'm guessing they are a mistake to be in the contract in the first place.

This is a really useful page to send beginners but confusing when the first example doesn't work. So would be great to get this updated. Just remove the following lines from the token code:

  function burn() payable returns (bool success) {
        if (balanceOf[_from] < _value) throw;                 // Check if the sender has enough
        balanceOf[_from] -= _value;                          // Subtract from the sender
        Burn(_from, _value);
        return true;
    }

    function burnFrom(address _from) payable returns (bool success) {
        if (balanceOf[_from] < _value) throw;                 // Check if the sender has enough
        if (_value > allowance[_from][msg.sender]) throw;   // Check allowance
        balanceOf[_from] -= _value;                          // Subtract from the sender
        Burn(_from, _value);
        return true;
    }

**Comment by dgobaud** [comment]
Just ran into this problem myself

**Comment by thanos** [comment]
Can someone explain or add a link explaining these functions - many thanks

**Comment by alexvandesande** [comment]
code has been fixed, thanks! I kept the burn functions as they are important if you are just putting a default token out there

**Comment by howtomakeaturn** [comment]
@alexvandesande 

What does 'they are important if you are just putting a default token out there' mean?

Since it's not explained in the documentation, can you explain a bit more?

Thanks for any feedback!

**Comment by alexvandesande** [comment]
The token code disallows people to send tokens to 0x000 by mistake. This removes also the most common way of burning tokens, therefore the added function. Of course it's just an example
