### ISSUE TITLE
Default token implementation does not work with new release of mist

### ISSUE THREAD

**Issue by xlcrr** [ethereum/ethereum-org#589]
Pretty sure this was working with the last release

Line 63
    /* Allow another contract to spend some tokens in your behalf */
    function approve(address _spender, uint256 _value)
        returns (bool success) {
        allowance[msg.sender][_spender] = _value;
        tokenRecipient spender = tokenRecipient(_spender); // 63
        return true;
    }

throws:
 Unused local variable
        tokenRecipient spender = tokenRecipient(_spender);

**Comment by alexvandesande** [comment]
code has been fixed, thanks!
