### ISSUE TITLE
Block frequency inconsistency

### ISSUE THREAD

**Issue by nfriedly** [ethereum/ethereum-org#632]
In the FAQ on https://www.ethereum.org/ether it says:

> * 5 ethers are created every block (roughly 15-17 seconds) to the miner of the block

But, under "How do I mine ether?", it says:

> Every 12 seconds, on average, a new block is added to the blockchain with the latest transactions processed by the network and the computer that generated this block will be awarded 5 ether. 

I've seen both numbers (and a couple of others) quoted around the internet, so I'm not really sure which is correct.. but the page should probably at least be consistent.

**Comment by adhikasp** [comment]
I think both of those page is outdated. After the Byzantium hf, the [block reward is reduced to 3 ETH](https://blog.ethereum.org/2017/10/12/byzantium-hf-announcement/) and [avg block time is 15 s](https://ethstats.net/).
