### ISSUE TITLE
Add page for notable new/upcoming ICO projects

### ISSUE THREAD

**Issue by gtseres** [ethereum/ethereum-org#652]
Another section could be added that lists the most notable recent or upcoming Ethereum-based tokens/ICOs. This will help in helping those ICOs gain attention, helping both the token and Ethereum to increase their adoption.

Not sure if this is the right place for this enhancement request, as it may touch non-technical aspects, as for example how the 'most notable' projects are going to be defined.

**Comment by evertonfraga** [comment]
EF will not promote ICOs.

Afaik, there's some discussion about a refreshed website and it might comprise relevant community projects.
