### ISSUE TITLE
Broken warning modal shown up in page

### ISSUE THREAD

**Issue by adhikasp** [ethereum/ethereum-org#716]
See this ![pics](https://i.gyazo.com/ee9a1a5aaa9eb75e832685867390803a.png)

Seems like the warning modal that usually popup on download wallet button is shown up in the page.
And also the download button itself is not working.

Tested on latest chrome & firefox

**Comment by cleanforestco** [comment]
Should be fixed via PR: https://github.com/ethereum/ethereum-org/pull/719

**Comment by cleanforestco** [comment]
This should be fixed now.
https://github.com/ethereum/ethereum-org/commit/b1319b80c3d981dec26f97080e785645823da4df
