### ISSUE TITLE
Functions in interfaces should be declared external. TokenERC20 Contract

### ISSUE THREAD

**Issue by Grey007** [ethereum/ethereum-org#809]
Hi, 

I am receiving the following error when using the TokenERC20:

``` Functions in interfaces should be declared external.
interface tokenRecipient { function receiveApproval(address _from, uint256 _value, address _token, bytes _extraData) public; }
                           ^-----------------------------------------------------------------------------------------------^

**Comment by YuxuanLin** [comment]
Same here

**Comment by scottie** [comment]
change "public" at the end to "external".
I will agree its pathetic such a large for profit money making venture cant even make there demos correct, yet the foundation dont mind dumping into there supporter's....
You might want to look elsewhere for any real support.

**Comment by avatar-lavventura** [comment]
When I replace `public` with `external` keyword I am getting following error message:

`Location has to be calldata for external functions (remove the "memory" or "storage" keyword).`
