### ISSUE TITLE
OSX Building from Source link is 404

### ISSUE THREAD

**Issue by debragail** [ethereum/ethereum-org#856]
https://www.ethereum.org/cli
<img width="1210" alt="screen shot 2018-05-31 at 13 39 46" src="https://user-images.githubusercontent.com/552529/40807058-1fbbe0f4-64d8-11e8-9460-2632751a0bf5.png">

<img width="1596" alt="screen shot 2018-05-31 at 13 37 44" src="https://user-images.githubusercontent.com/552529/40807004-fb6ce2f2-64d7-11e8-9439-f7f2e12c5b74.png">

**Comment by evertonfraga** [comment]
Thanks for reporting! 

to prevent this from happening again, I've added a test that looks for broken links. So far, it discovered 11 entries: https://travis-ci.org/ethereum/ethereum-org/builds/389789947?utm_source=github_status&utm_medium=notification
