### ISSUE TITLE
ethereum wallet keeps loading

### ISSUE THREAD

**Issue by gmonkey360** [ethereum/ethereum-org#896]
my problem is that every time I keep opening the ethereum wallet it doesn't load. I have it running at this moment and it just keeps showing that it is still loading. I know that they have been having trouble with the windows version where it only goes to a white page, but this is actually just loading the entire time. What should I try and do I have already uninstalled the software and reloaded it and some how still have the same problem.  Any thoughts would be useful.

**Comment by evertonfraga** [comment]
Hi, you can find help for your issue here: https://github.com/ethereum/mist

**Comment by ghost** [comment]
Same issue
